// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: switch

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
#define NUM_SWITCHES  5 //Number switch you want to use
bool switch_states[NUM_SWITCHES] = {false}; //Set the initial state of the switch to false.

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel2;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
void ui_event_Switch4(lv_event_t * e);
lv_obj_t * ui_Switch4;
void ui_event_Switch5(lv_event_t * e);
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Image5;
void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Image6;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_Chart1_Xaxis;
lv_obj_t * ui_Chart1_Yaxis1;
lv_obj_t * ui_Chart1_Yaxis2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
void ui_event_ImgButton2(lv_event_t * e);
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[0] = lv_obj_has_state(target, LV_STATE_CHECKED);


         if (switch_states[0]) {
            switch_states[1] = true;
            switch_states[2] = true;
            switch_states[3] = true;
            switch_states[4] = true;
            _ui_state_modify(ui_Switch2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_state_modify(ui_Switch3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_state_modify(ui_Switch4, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_state_modify(ui_Switch5, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &ui_img_onlight_png);
            _ui_image_set_property(ui_Image2, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_onlight_png);
            _ui_image_set_property(ui_Image3, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_onlight_png);
            _ui_image_set_property(ui_Image4, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_onlight_png);
        } 
        // If SW0 is off, turn off all (but can still be turned on individually).
        else {
            switch_states[1] = false;
            switch_states[2] = false;
            switch_states[3] = false;
            switch_states[4] = false;
            _ui_state_modify(ui_Switch2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_Switch3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_Switch4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_Switch5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_offlight_png);
            _ui_image_set_property(ui_Image2, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_offlight_png);
            _ui_image_set_property(ui_Image3, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_offlight_png);
            _ui_image_set_property(ui_Image4, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_offlight_png);
        }
        _ui_checked_set_text_value(ui_Label1, target, "ALL ON", "ALL OFF");

    }
}
void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[1] = lv_obj_has_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, switch_states[1] ? & ui_img_onlight_png : & ui_img_offlight_png);
       
         //Check if both all are on, then SW0 will turn on automatically.
        if (switch_states[1] && switch_states[2] && switch_states[3] && switch_states[4]) {
            switch_states[0] = true;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        } else if (!switch_states[1] && !switch_states[2] && !switch_states[3] && !switch_states[4]) {
            switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
        //When SW1 OFF, then SW0 is off
        if (!switch_states[1]){
             switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
    }
}


void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[2] = lv_obj_has_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image2, _UI_IMAGE_PROPERTY_IMAGE, switch_states[2] ? & ui_img_onlight_png : & ui_img_offlight_png);
       
         //Check if both all are on, then SW0 will turn on automatically.
        if (switch_states[1] && switch_states[2] && switch_states[3] && switch_states[4]) {
            switch_states[0] = true;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        } else if (!switch_states[1] && !switch_states[2] && !switch_states[3] && !switch_states[4]) {
            switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
        //When SW2 OFF, then SW0 is off
        if (!switch_states[2]){
             switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
    }
}
void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[3] = lv_obj_has_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image3, _UI_IMAGE_PROPERTY_IMAGE, switch_states[3] ? & ui_img_onlight_png : & ui_img_offlight_png);
       
         //Check if both all are on, then SW0 will turn on automatically.
        if (switch_states[1] && switch_states[2] && switch_states[3] && switch_states[4]) {
            switch_states[0] = true;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        } else if (!switch_states[1] && !switch_states[2] && !switch_states[3] && !switch_states[4]) {
            switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
        //When SW3 OFF, then SW0 is off
        if (!switch_states[3]){
             switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
    }
}
void ui_event_Switch5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[4] = lv_obj_has_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image4, _UI_IMAGE_PROPERTY_IMAGE, switch_states[4] ? & ui_img_onlight_png : & ui_img_offlight_png);
       
         //Check if both all are on, then SW0 will turn on automatically.
        if (switch_states[1] && switch_states[2] && switch_states[3] && switch_states[4]) {
            switch_states[0] = true;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        } else if (!switch_states[1] && !switch_states[2] && !switch_states[3] && !switch_states[4]) {
            switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
        //When SW4 OFF, then SW0 is off
        if (!switch_states[4]){
             switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
    }
}

/** Button event for change screen **/
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
