// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: switch

#ifndef _SWITCH_UI_H
#define _SWITCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#define NUM_SWITCHES 
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel2;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
void ui_event_Switch5(lv_event_t * e);
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image5;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image6;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui____initial_actions0;

extern lv_chart_series_t * ui_Chart1_series_1;
extern lv_chart_series_t * ui_Chart1_series_2;

extern bool switch_states[NUM_SWITCHES];


//LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_onlight_png);    // assets/OnLight.png
LV_IMG_DECLARE(ui_img_offlight_png);    // assets/OffLight.png
LV_IMG_DECLARE(ui_img_transoff_png);    // assets/transOff.png
LV_IMG_DECLARE(ui_img_graph_png);    // assets/graph.png
LV_IMG_DECLARE(ui_img_transon_png);    // assets/transOn.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
